services:
  mysql:
    image: mysql:8.0
    container_name: kanban-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanban
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: kanban-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  mysql_data:
  redis_data:
