server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/github
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASS_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kanban
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb+srv://bacpham:${PASSWORD_MONGODB}@cluster0.vlmwfvo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        completions-path: v1beta/models/gemini-2.0-flash:generateContent
        base-url: https://generativelanguage.googleapis.com
        options:
          model: gemini-2.0-flash

application:
  oauth2:
    authorized-redirect-uri: http://localhost:3004/auth/oauth-callback
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000

      refresh-token:
        expiration: 604800000
logging:
  level:
    org.springframework.security: DEBUG