server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kanban
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        completions-path: v1beta/models/gemini-2.0-flash:generateContent
        base-url: https://generativelanguage.googleapis.com
        options:
          model: gemini-2.0-flash

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 8640000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
